/* eslint-disable */
// source: home.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.home.FetchHomePreviewRecordsRequest', null, global);
goog.exportSymbol('proto.home.FetchHomePreviewRecordsResponse', null, global);
goog.exportSymbol('proto.home.HomePreveiwRecordItem', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.home.FetchHomePreviewRecordsRequest = function(opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.home.FetchHomePreviewRecordsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    proto.home.FetchHomePreviewRecordsRequest.displayName = 'proto.home.FetchHomePreviewRecordsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.home.HomePreveiwRecordItem = function(opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, proto.home.HomePreveiwRecordItem.repeatedFields_, null);
};
goog.inherits(proto.home.HomePreveiwRecordItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    proto.home.HomePreveiwRecordItem.displayName = 'proto.home.HomePreveiwRecordItem';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.home.FetchHomePreviewRecordsResponse = function(opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, proto.home.FetchHomePreviewRecordsResponse.repeatedFields_, null);
};
goog.inherits(proto.home.FetchHomePreviewRecordsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    proto.home.FetchHomePreviewRecordsResponse.displayName = 'proto.home.FetchHomePreviewRecordsResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.home.FetchHomePreviewRecordsRequest.prototype.toObject = function(opt_includeInstance) {
        return proto.home.FetchHomePreviewRecordsRequest.toObject(opt_includeInstance, this);
    };


    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.home.FetchHomePreviewRecordsRequest} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.home.FetchHomePreviewRecordsRequest.toObject = function(includeInstance, msg) {
        var f, obj = {

        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.home.FetchHomePreviewRecordsRequest}
 */
proto.home.FetchHomePreviewRecordsRequest.deserializeBinary = function(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.home.FetchHomePreviewRecordsRequest;
    return proto.home.FetchHomePreviewRecordsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.home.FetchHomePreviewRecordsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.home.FetchHomePreviewRecordsRequest}
 */
proto.home.FetchHomePreviewRecordsRequest.deserializeBinaryFromReader = function(msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            default: reader.skipField();
            break;
        }
    }
    return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.home.FetchHomePreviewRecordsRequest.prototype.serializeBinary = function() {
    var writer = new jspb.BinaryWriter();
    proto.home.FetchHomePreviewRecordsRequest.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.home.FetchHomePreviewRecordsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.home.FetchHomePreviewRecordsRequest.serializeBinaryToWriter = function(message, writer) {
    var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.home.HomePreveiwRecordItem.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.home.HomePreveiwRecordItem.prototype.toObject = function(opt_includeInstance) {
        return proto.home.HomePreveiwRecordItem.toObject(opt_includeInstance, this);
    };


    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.home.HomePreveiwRecordItem} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.home.HomePreveiwRecordItem.toObject = function(includeInstance, msg) {
        var f, obj = {
            id: jspb.Message.getFieldWithDefault(msg, 1, ""),
            spaceid: jspb.Message.getFieldWithDefault(msg, 2, ""),
            title: jspb.Message.getFieldWithDefault(msg, 3, ""),
            date: (f = msg.getDate()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
            tagsList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.home.HomePreveiwRecordItem}
 */
proto.home.HomePreveiwRecordItem.deserializeBinary = function(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.home.HomePreveiwRecordItem;
    return proto.home.HomePreveiwRecordItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.home.HomePreveiwRecordItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.home.HomePreveiwRecordItem}
 */
proto.home.HomePreveiwRecordItem.deserializeBinaryFromReader = function(msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = /** @type {string} */ (reader.readString());
                msg.setId(value);
                break;
            case 2:
                var value = /** @type {string} */ (reader.readString());
                msg.setSpaceid(value);
                break;
            case 3:
                var value = /** @type {string} */ (reader.readString());
                msg.setTitle(value);
                break;
            case 4:
                var value = new google_protobuf_timestamp_pb.Timestamp;
                reader.readMessage(value, google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
                msg.setDate(value);
                break;
            case 5:
                var value = /** @type {string} */ (reader.readString());
                msg.addTags(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.home.HomePreveiwRecordItem.prototype.serializeBinary = function() {
    var writer = new jspb.BinaryWriter();
    proto.home.HomePreveiwRecordItem.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.home.HomePreveiwRecordItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.home.HomePreveiwRecordItem.serializeBinaryToWriter = function(message, writer) {
    var f = undefined;
    f = message.getId();
    if (f.length > 0) {
        writer.writeString(
            1,
            f
        );
    }
    f = message.getSpaceid();
    if (f.length > 0) {
        writer.writeString(
            2,
            f
        );
    }
    f = message.getTitle();
    if (f.length > 0) {
        writer.writeString(
            3,
            f
        );
    }
    f = message.getDate();
    if (f != null) {
        writer.writeMessage(
            4,
            f,
            google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
        );
    }
    f = message.getTagsList();
    if (f.length > 0) {
        writer.writeRepeatedString(
            5,
            f
        );
    }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.home.HomePreveiwRecordItem.prototype.getId = function() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.home.HomePreveiwRecordItem} returns this
 */
proto.home.HomePreveiwRecordItem.prototype.setId = function(value) {
    return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string spaceId = 2;
 * @return {string}
 */
proto.home.HomePreveiwRecordItem.prototype.getSpaceid = function() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.home.HomePreveiwRecordItem} returns this
 */
proto.home.HomePreveiwRecordItem.prototype.setSpaceid = function(value) {
    return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string title = 3;
 * @return {string}
 */
proto.home.HomePreveiwRecordItem.prototype.getTitle = function() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.home.HomePreveiwRecordItem} returns this
 */
proto.home.HomePreveiwRecordItem.prototype.setTitle = function(value) {
    return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional google.protobuf.Timestamp date = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.home.HomePreveiwRecordItem.prototype.getDate = function() {
    return /** @type{?proto.google.protobuf.Timestamp} */ (
        jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.home.HomePreveiwRecordItem} returns this
 */
proto.home.HomePreveiwRecordItem.prototype.setDate = function(value) {
    return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.home.HomePreveiwRecordItem} returns this
 */
proto.home.HomePreveiwRecordItem.prototype.clearDate = function() {
    return this.setDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.home.HomePreveiwRecordItem.prototype.hasDate = function() {
    return jspb.Message.getField(this, 4) != null;
};


/**
 * repeated string tags = 5;
 * @return {!Array<string>}
 */
proto.home.HomePreveiwRecordItem.prototype.getTagsList = function() {
    return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 5));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.home.HomePreveiwRecordItem} returns this
 */
proto.home.HomePreveiwRecordItem.prototype.setTagsList = function(value) {
    return jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.home.HomePreveiwRecordItem} returns this
 */
proto.home.HomePreveiwRecordItem.prototype.addTags = function(value, opt_index) {
    return jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.home.HomePreveiwRecordItem} returns this
 */
proto.home.HomePreveiwRecordItem.prototype.clearTagsList = function() {
    return this.setTagsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.home.FetchHomePreviewRecordsResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.home.FetchHomePreviewRecordsResponse.prototype.toObject = function(opt_includeInstance) {
        return proto.home.FetchHomePreviewRecordsResponse.toObject(opt_includeInstance, this);
    };


    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.home.FetchHomePreviewRecordsResponse} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.home.FetchHomePreviewRecordsResponse.toObject = function(includeInstance, msg) {
        var f, obj = {
            recordsList: jspb.Message.toObjectList(msg.getRecordsList(),
                proto.home.HomePreveiwRecordItem.toObject, includeInstance)
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.home.FetchHomePreviewRecordsResponse}
 */
proto.home.FetchHomePreviewRecordsResponse.deserializeBinary = function(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.home.FetchHomePreviewRecordsResponse;
    return proto.home.FetchHomePreviewRecordsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.home.FetchHomePreviewRecordsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.home.FetchHomePreviewRecordsResponse}
 */
proto.home.FetchHomePreviewRecordsResponse.deserializeBinaryFromReader = function(msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = new proto.home.HomePreveiwRecordItem;
                reader.readMessage(value, proto.home.HomePreveiwRecordItem.deserializeBinaryFromReader);
                msg.addRecords(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.home.FetchHomePreviewRecordsResponse.prototype.serializeBinary = function() {
    var writer = new jspb.BinaryWriter();
    proto.home.FetchHomePreviewRecordsResponse.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.home.FetchHomePreviewRecordsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.home.FetchHomePreviewRecordsResponse.serializeBinaryToWriter = function(message, writer) {
    var f = undefined;
    f = message.getRecordsList();
    if (f.length > 0) {
        writer.writeRepeatedMessage(
            1,
            f,
            proto.home.HomePreveiwRecordItem.serializeBinaryToWriter
        );
    }
};


/**
 * repeated HomePreveiwRecordItem records = 1;
 * @return {!Array<!proto.home.HomePreveiwRecordItem>}
 */
proto.home.FetchHomePreviewRecordsResponse.prototype.getRecordsList = function() {
    return /** @type{!Array<!proto.home.HomePreveiwRecordItem>} */ (
        jspb.Message.getRepeatedWrapperField(this, proto.home.HomePreveiwRecordItem, 1));
};


/**
 * @param {!Array<!proto.home.HomePreveiwRecordItem>} value
 * @return {!proto.home.FetchHomePreviewRecordsResponse} returns this
 */
proto.home.FetchHomePreviewRecordsResponse.prototype.setRecordsList = function(value) {
    return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.home.HomePreveiwRecordItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.home.HomePreveiwRecordItem}
 */
proto.home.FetchHomePreviewRecordsResponse.prototype.addRecords = function(opt_value, opt_index) {
    return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.home.HomePreveiwRecordItem, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.home.FetchHomePreviewRecordsResponse} returns this
 */
proto.home.FetchHomePreviewRecordsResponse.prototype.clearRecordsList = function() {
    return this.setRecordsList([]);
};


goog.object.extend(exports, proto.home);