export const INTERNAL_PART_UPDATE = 'INTERNAL_PART_UPDATE';
export const INTERNAL_ADD_STATE_IF_NO_EXISTS = 'INTERNAL_ADD_STATE_IF_NO_EXISTS';
export const INTERNAL_Remove_STATE_IF_EXISTS = 'INTERNAL_Remove_STATE_IF_EXISTS';

export const CREATE_NEW_RECORD = 'CREATE_NEW_RECORD';